name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: install libudev-dev
      run: sudo apt-get install libudev-dev
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
    - name: make
      run: make VERBOSE=1
    - name: make package
      run: make package
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: packages
    - uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./packages/*
        tag: develop
    - name: cmake2
      run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=artifacts -DINSTALL_COMPLETION=off .
    - name: make2
      run: make VERBOSE=1
    - name: make install
      run: make install
    - name: archive
      run: tar -czf artifacts.tgz artifacts/ 
    - name: Archive production artifacts2
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: artifacts.tgz
    - uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./artifacts.tgz
        tag: develop
